# Generated by Django 2.1.5 on 2020-03-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200306_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
