# Generated by Django 2.1.5 on 2020-03-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200306_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='staff_img/%Y/%m/%d', verbose_name='Own Picture', width_field='width_field'),
        ),
    ]
