# Generated by Django 2.1.5 on 2020-03-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200312_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/staff.png', height_field='height_field', null=True, upload_to='staff_img/%Y/%m/%d', verbose_name='Own Picture', width_field='width_field'),
        ),
    ]
